spring:
  application:
    name: UberBookingService

  datasource:
    url: jdbc:mysql://localhost:3306/Uber_Db_Local
    username: ${DB_USERNAME:abhinav}
    password: ${DB_PASSWORD:pass123}

  kafka:
    bootstrap-servers: localhost:9092
    group-id: test-group
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  jpa:
    show-sql: true

server:
  port: 8082